#!/usr/bin/env bash
# Experiment B — under-training / schedule-length confound check.
#
# Tests whether the depth-graded, late-sensitive response is an artifact of the
# 80-epoch no-schedule controlled regime, by varying ONLY the training budget
# (and, separately, ONLY a cosine schedule) while holding the controlled regime
# (no aug / no momentum / no WD, base LR 0.04096) fixed. This is the clean
# one-variable test that the existing practical-recipe null cannot provide,
# because the practical recipe moves budget+schedule+aug+momentum+WD together.
#
# Arms (all in the controlled regime):
#   1. budget ladder   : max_epochs in {80,160,320}, lr_scheduler=none
#   2. schedule-only   : max_epochs=80, lr_scheduler=cosine
#   3. depth ordering  : full 9-block cut sweep (2..8) at max_epochs=320
#                        (re-tests the Spearman-rho ordering at the long budget)
#
# Pair = matched GLOBAL FLS reference (experiment_B_global_ref.yaml, global c=0.25)
#        vs after-late boundary (imp_pos_base.yaml, position=8, c=0.0625).
# Both use upstream LR compensation, seeds 0-4, base LR 0.04096.
#
# Usage:
#   scripts/launch_B_budget_ladder.sh            # FULL (arms 1-3, seeds 0-4)
#   B_SCOPE=min scripts/launch_B_budget_ladder.sh # MIN (arms 1-2 only, seeds 0-2)
#   B_SCOPE=budget_schedule scripts/launch_B_budget_ladder.sh # arms 1-2, seeds 0-4
#
# Compute note: the max_epochs=320 jobs (arm 1 endpoint + all of arm 3) are the
# expensive tail (~4x an 80-epoch run each). Start MIN, inspect, then run FULL.
set -u
cd "$(dirname "$0")/.."
PY=./.venv/bin/python
GPUS="${B_GPUS:-0,1}"
SCOPE="${B_SCOPE:-full}"
JOBS=configs/jobs_wave_B.txt
LOGDIR=outputs/_pool_logs_B
GLOBAL=configs/experiment_B_global_ref.yaml
LATE=configs/imp_pos_base.yaml

if [ "$SCOPE" = "min" ]; then SEEDS="0 1 2"; else SEEDS="0 1 2 3 4"; fi

mkdir -p "$LOGDIR" outputs/imp_analysis
: > "$JOBS"
{
  echo "# Experiment B jobs (scope=$SCOPE). Generated by launch_B_budget_ladder.sh."
  echo "# matched pair: global c=0.25 vs after-late (position=8) c=0.0625, controlled regime, LR 0.04096."

  # --- Arm 1: budget ladder, no schedule (diagnostics ON to track the representation signature) ---
  for E in 80 160 320; do
    for S in $SEEDS; do
      echo "$GLOBAL training.seed=$S training.max_epochs=$E training.lr_scheduler=none diagnostics.enabled=true experiment.name=B_global_ep${E}"
      echo "$LATE training.seed=$S training.max_epochs=$E training.lr_scheduler=none fls.position=8 fls.output_multiplier=0.0625 diagnostics.enabled=true experiment.name=B_late_ep${E}"
    done
  done

  # --- Arm 2: schedule-only (cosine at 80 epochs), isolates "scheduled" from "longer" ---
  for S in $SEEDS; do
    echo "$GLOBAL training.seed=$S training.max_epochs=80 training.lr_scheduler=cosine diagnostics.enabled=true experiment.name=B_global_ep80_cos"
    echo "$LATE training.seed=$S training.max_epochs=80 training.lr_scheduler=cosine fls.position=8 fls.output_multiplier=0.0625 diagnostics.enabled=true experiment.name=B_late_ep80_cos"
  done

  # --- Arm 3: depth ordering at the long budget (only in FULL scope) ---
  if [ "$SCOPE" = "full" ]; then
    for S in $SEEDS; do
      echo "$LATE training.seed=$S training.max_epochs=320 training.lr_scheduler=none fls.position=8 fls.output_multiplier=1.0 experiment.name=B_pos_baseline_ep320"
      for CUT in 2 3 4 5 6 7 8; do
        echo "$LATE training.seed=$S training.max_epochs=320 training.lr_scheduler=none fls.position=${CUT} fls.output_multiplier=0.0625 experiment.name=B_pos_cut${CUT}_ep320"
      done
    done
  fi
} >> "$JOBS"

echo "[B] $(date) generated $(grep -vc '^#' "$JOBS") jobs in $JOBS (scope=$SCOPE, gpus=$GPUS)."
$PY scripts/gpu_pool_run.py --jobs "$JOBS" --gpus "$GPUS" --logdir "$LOGDIR" \
  > outputs/_pool_logs_B.log 2>&1
echo "[B] $(date) ALL B DONE. Summarize with scripts/summarize_experiments.py over outputs/B_* ."
