#!/usr/bin/env python
"""Aggregate the validation-selected budget/schedule sensitivity experiment.

The script reads the paired global and after-late runs generated by
``scripts/launch_B_budget_ladder.sh``.  Within each run, the earliest epoch
attaining the maximum validation accuracy selects the reported test accuracy.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import math
import statistics
from pathlib import Path

from scipy import stats


CONDITIONS = (
    ("80 epochs, no schedule", 80, "none", "B_global_ep80", "B_late_ep80"),
    ("160 epochs, no schedule", 160, "none", "B_global_ep160", "B_late_ep160"),
    ("320 epochs, no schedule", 320, "none", "B_global_ep320", "B_late_ep320"),
    ("80 epochs, cosine", 80, "cosine", "B_global_ep80_cos", "B_late_ep80_cos"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--outputs-root", type=Path, default=Path("outputs"))
    parser.add_argument(
        "--output-dir", type=Path, default=Path("results/paper")
    )
    parser.add_argument("--seeds", type=int, nargs="+", default=list(range(5)))
    return parser.parse_args()


def find_metrics(outputs_root: Path, experiment: str, seed: int) -> Path:
    matches = sorted(outputs_root.glob(f"{experiment}/*/seed_{seed}/metrics.csv"))
    if not matches:
        raise FileNotFoundError(f"No metrics.csv for {experiment}, seed {seed}")
    return matches[-1]


def selected_row(path: Path) -> dict[str, float | int]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    eligible = [
        row
        for row in rows
        if row.get("val_accuracy") not in {None, ""}
        and row.get("test_accuracy") not in {None, ""}
    ]
    if not eligible:
        raise ValueError(f"No validation/test rows in {path}")
    best = min(
        eligible,
        key=lambda row: (-float(row["val_accuracy"]), int(row["epoch"])),
    )
    return {
        "selected_epoch": int(best["epoch"]),
        "validation_accuracy_percent": 100.0 * float(best["val_accuracy"]),
        "test_accuracy_percent": 100.0 * float(best["test_accuracy"]),
    }


def exact_sign_flip_p(differences: list[float]) -> float:
    observed = abs(statistics.mean(differences))
    permuted = [
        abs(statistics.mean(sign * value for sign, value in zip(signs, differences)))
        for signs in itertools.product((-1.0, 1.0), repeat=len(differences))
    ]
    return sum(value >= observed - 1e-12 for value in permuted) / len(permuted)


def summarize(values: list[float]) -> tuple[float, float]:
    return statistics.mean(values), statistics.stdev(values)


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    seed_rows: list[dict[str, float | int | str]] = []
    summary_rows: list[dict[str, float | int | str | bool]] = []

    for label, budget, scheduler, global_name, late_name in CONDITIONS:
        differences: list[float] = []
        global_values: list[float] = []
        late_values: list[float] = []
        for seed in args.seeds:
            global_row = selected_row(find_metrics(args.outputs_root, global_name, seed))
            late_row = selected_row(find_metrics(args.outputs_root, late_name, seed))
            difference = (
                float(late_row["test_accuracy_percent"])
                - float(global_row["test_accuracy_percent"])
            )
            global_values.append(float(global_row["test_accuracy_percent"]))
            late_values.append(float(late_row["test_accuracy_percent"]))
            differences.append(difference)
            seed_rows.append(
                {
                    "condition": label,
                    "budget_epochs": budget,
                    "scheduler": scheduler,
                    "seed": seed,
                    "global_selected_epoch": global_row["selected_epoch"],
                    "late_selected_epoch": late_row["selected_epoch"],
                    "global_test_accuracy_percent": global_row["test_accuracy_percent"],
                    "late_test_accuracy_percent": late_row["test_accuracy_percent"],
                    "late_minus_global_pp": difference,
                }
            )

        global_mean, global_sd = summarize(global_values)
        late_mean, late_sd = summarize(late_values)
        difference_mean, difference_sd = summarize(differences)
        half_width = float(stats.t.ppf(0.975, len(differences) - 1)) * difference_sd / math.sqrt(
            len(differences)
        )
        summary_rows.append(
            {
                "condition": label,
                "budget_epochs": budget,
                "scheduler": scheduler,
                "n_paired_seeds": len(differences),
                "seeds": ";".join(str(seed) for seed in args.seeds),
                "global_mean_percent": global_mean,
                "global_sd_percent": global_sd,
                "late_mean_percent": late_mean,
                "late_sd_percent": late_sd,
                "late_minus_global_mean_pp": difference_mean,
                "late_minus_global_sd_pp": difference_sd,
                "ci95_low_pp": difference_mean - half_width,
                "ci95_high_pp": difference_mean + half_width,
                "exact_sign_flip_p": exact_sign_flip_p(differences),
                "all_selected_before_epoch_30": all(
                    int(row["global_selected_epoch"]) < 30
                    and int(row["late_selected_epoch"]) < 30
                    for row in seed_rows
                    if row["condition"] == label
                ),
            }
        )

    for filename, rows in (
        ("budget_schedule_seed_level.csv", seed_rows),
        ("budget_schedule_summary.csv", summary_rows),
    ):
        path = args.output_dir / filename
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
